sudo: required
services:
  - docker

before_install:
  - docker build -t patrickblais/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run patrickblais/react-test npm test -- --coverage

after_success:
  - docker build -t patrickblais/multi-client ./client
  - docker build -t patrickblais/multi-nginx ./nginx
  - docker build -t patrickblais/multi-server ./server
  - docker build -t patrickblais/multi-worker ./worker
# Log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#PUSH TO DOCKERHUB
  - docker push patrickblais/multi-client
  - docker push patrickblais/multi-nginx
  - docker push patrickblais/multi-server
  - docker push patrickblais/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-072921345302"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
